gitee:
  client:
    id: f4a1508fb097efd7db3eba8a125450de788695c0af55bdbc3afc20bb580ae58e
    secret: 550a55c2538fd2ed7263af72c3dfe0d271248acfc4ef66e674b23954a17b24db
  redirect:
    url: http://liangyijian.free.idcfengye.com/callback

spring:
  datasource:
    username: root
    password: lyj666
    url: jdbc:mysql://localhost:3306/community?rewriteBatchedStatements=true
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

